name: CI

on: [push, pull_request]

jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node_version:
          - 16
          - 14
          - 12
          - 10
    runs-on: ${{ matrix.os }}
    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Node.js packages
        run: npm install
      - name: Run tests
        run: npm test
